# Generated by Django 2.0.1 on 2018-03-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('I', 'In-Stock')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
