# Generated by Django 2.0.1 on 2018-04-04 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databse', '0004_auto_20180401_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-OrderDate',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Fname',
            field=models.CharField(default='jon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Lname',
            field=models.CharField(default='smith', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='ny', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='@gmail', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('P', 'Paid'), ('S', 'Shipping'), ('R', 'Recieved')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select a category for this product', to='databse.Category'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='databse.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='databse.Product'),
        ),
    ]
